# Hydrogram A and B (Resolução ANA 911-2014) for Belo Monte
# http://arquivos.ana.gov.br/resolucoes/2014/ANALegis/LEGISResolucao911-2014.pdf
# The position of each value indicates the month (0: january, 1: february, ..., 11: december)
hydrogram = {
    'A': [1100, 1600, 2500, 4000, 1800, 1200, 1000, 900, 750, 700, 800, 900],
    'B': [1100, 1600, 4000, 8000, 4000, 2000, 1200, 900, 750, 700, 800, 900],
    'A_B': [1100, 1600, 3250, 6000, 2900, 1600, 1100, 900, 750, 700, 800, 900],
    'IBAMA': [3100, 10900, 14200, 13400, 5200, 1800, 1300, 900, 750, 760, 1000, 1200]
}

hydrogram_used = hydrogram['B']

# Dictionary containing the natural and artificial code for each station
stations_code = {
1: {'name': ['Camargos'], 'id_nat': [1], 'id_art': [None]},
2: {'name': ['Itutinga'], 'id_nat': [2], 'id_art': [None]},
4: {'name': ['Funil-MG'], 'id_nat': [211], 'id_art': [None]},
6: {'name': ['Furnas'], 'id_nat': [6], 'id_art': [None]},
7: {'name': ['Mascarenhas de Moraes'], 'id_nat': [7], 'id_art': [None]},
8: {'name': ['Estreito'], 'id_nat': [8], 'id_art': [None]},
9: {'name': ['Jaguara'], 'id_nat': [9], 'id_art': [None]},
10: {'name': ['Igarapava'], 'id_nat': [10], 'id_art': [None]},
11: {'name': ['Volta Grande'], 'id_nat': [11], 'id_art': [None]},
12: {'name': ['Porto Colômbia'], 'id_nat': [12], 'id_art': [None]},
14: {'name': ['Caconde'], 'id_nat': [14], 'id_art': [None]},
15: {'name': ['Euclides da Cunha'], 'id_nat': [15], 'id_art': [None]},
16: {'name': ['Limoeiro'], 'id_nat': [16], 'id_art': [None]},
17: {'name': ['Marimbondo'], 'id_nat': [17], 'id_art': [None]},
18: {'name': ['Água Vermelha'], 'id_nat': [18], 'id_art': [None]},
20: {'name': ['Batalha'], 'id_nat': [22], 'id_art': [None]},
21: {'name': ['Serra do Facão'], 'id_nat': [251], 'id_art': [None]},
24: {'name': ['Emborcação'], 'id_nat': [24], 'id_art': [None]},
25: {'name': ['Nova Ponte'], 'id_nat': [25], 'id_art': [None]},
26: {'name': ['Miranda'], 'id_nat': [206], 'id_art': [None]},
27: {'name': ['Capim Branco 1'], 'id_nat': [207], 'id_art': [None]},
28: {'name': ['Capim Branco 2'], 'id_nat': [28], 'id_art': [None]},
29: {'name': ['Corumbá IV'], 'id_nat': [205], 'id_art': [None]},
30: {'name': ['Corumbá I'], 'id_nat': [209], 'id_art': [None]},
31: {'name': ['Itumbiara'], 'id_nat': [31], 'id_art': [None]},
32: {'name': ['Cachoeira Dourada'], 'id_nat': [32], 'id_art': [None]},
33: {'name': ['São Simão'], 'id_nat': [33], 'id_art': [None]},
34: {'name': ['Ilha Solteira', 'Ilha Solteira Equivalente'], 'id_nat': [34, 244], 'id_art': [None, 44]},
37: {'name': ['Barra Bonita'], 'id_nat': [237], 'id_art': [37]},
38: {'name': ['Bariri'], 'id_nat': [238], 'id_art': [38]},
39: {'name': ['Ibitinga'], 'id_nat': [239], 'id_art': [39]},
40: {'name': ['Promissão'], 'id_nat': [240], 'id_art': [40]},
42: {'name': ['Nova Avanhandava'], 'id_nat': [242], 'id_art': [42]},
43: {'name': ['Três Irmãos'], 'id_nat': [243], 'id_art': [43]},
45: {'name': ['Jupiá'], 'id_nat': [245], 'id_art': [45]},
46: {'name': ['Porto Primavera'], 'id_nat': [246], 'id_art': [46]},
47: {'name': ['Jurumirim'], 'id_nat': [47], 'id_art': [None]},
48: {'name': ['Piraju'], 'id_nat': [48], 'id_art': [None]},
49: {'name': ['Chavantes'], 'id_nat': [49], 'id_art': [None]},
50: {'name': ['Lucas Nogueira Garcez'], 'id_nat': [50], 'id_art': [None]},
51: {'name': ['Canoas 2'], 'id_nat': [51], 'id_art': [None]},
52: {'name': ['Canoas 1'], 'id_nat': [52], 'id_art': [None]},
54: {'name': ['Santa Branca do Tigagi'], 'id_nat': [54], 'id_art': [None]},
61: {'name': ['Capivara'], 'id_nat': [61], 'id_art': [None]},
62: {'name': ['Taquaruçu'], 'id_nat': [62], 'id_art': [None]},
63: {'name': ['Rosana'], 'id_nat': [63], 'id_art': [None]},
66: {'name': ['Itaipu'], 'id_nat': [266], 'id_art': [66]},
71: {'name': ['Santa Clara PR'], 'id_nat': [71], 'id_art': [None]},
72: {'name': ['Fundão'], 'id_nat': [72], 'id_art': [None]},
73: {'name': ['Jordão'], 'id_nat': [73], 'id_art': [70]},
74: {'name': ['Foz do Areia'], 'id_nat': [74], 'id_art': [None]},
76: {'name': ['Segredo'], 'id_nat': [76], 'id_art': [75]},
77: {'name': ['Salto Santiago'], 'id_nat': [77], 'id_art': [None]},
78: {'name': ['Salto Osório'], 'id_nat': [78], 'id_art': [None]},
82: {'name': ['Salto Caxias'], 'id_nat': [222], 'id_art': [None]},
83: {'name': ['Baixo Iguaçu'], 'id_nat': [81], 'id_art': [None]},
86: {'name': ['Barra Grande'], 'id_nat': [215], 'id_art': [None]},
88: {'name': ['São Roque'], 'id_nat': [88], 'id_art': [None]},
89: {'name': ['Garibaldi'], 'id_nat': [89], 'id_art': [None]},
90: {'name': ['Campos Novos'], 'id_nat': [216], 'id_art': [None]},
91: {'name': ['Machadinho'], 'id_nat': [217], 'id_art': [None]},
92: {'name': ['Itá'], 'id_nat': [92], 'id_art': [None]},
93: {'name': ['Passo Fundo'], 'id_nat': [93], 'id_art': [None]},
94: {'name': ['Monjolinho'], 'id_nat': [220], 'id_art': [None]},
95: {'name': ['Quebra Queixo'], 'id_nat': [286], 'id_art': [None]},
97: {'name': ['Castro Alves'], 'id_nat': [98], 'id_art': [None]},
98: {'name': ['Monte Claro'], 'id_nat': [97], 'id_art': [None]},
99: {'name': ['14 de Julho'], 'id_nat': [284], 'id_art': [None]},
101: {'name': ['São José'], 'id_nat': [102], 'id_art': [None]},
102: {'name': ['Passo São João'], 'id_nat': [103], 'id_art': [None]},
103: {'name': ['Foz Chapecó'], 'id_nat': [94], 'id_art': [None]},
105: {'name': ['Ponte Nova / Alto Tietê'], 'id_nat': [160], 'id_art': [None]},
# 107: {'name': ['Edgard de Souza (c/ tributários)', 'Edgard de Souza (s/ tributários)'], 'id_nat': [161, 164], 'id_art': [None, None]},
107: {'name': ['Edgard de Souza (c/ tributários)'], 'id_nat': [161], 'id_art': [None]},
108: {'name': ['Traição'], 'id_nat': [104], 'id_art': [None]},
109: {'name': ['Pedreira'], 'id_nat': [109], 'id_art': [None]},
110: {'name': ['Ernestina'], 'id_nat': [110], 'id_art': [None]},
111: {'name': ['Passo Real'], 'id_nat': [111], 'id_art': [None]},
112: {'name': ['Jacuí'], 'id_nat': [112], 'id_art': [None]},
113: {'name': ['Itaúba'], 'id_nat': [113], 'id_art': [None]},
114: {'name': ['Dona Francisca'], 'id_nat': [114], 'id_art': [None]},
115: {'name': ['Capivari Cachoeira'], 'id_nat': [115], 'id_art': [None]},
117: {'name': ['Guarapiranga'], 'id_nat': [117], 'id_art': [None]},
118: {'name': ['Billings'], 'id_nat': [118], 'id_art': [None]},
119: {'name': ['Pedras', 'Billings + Pedras', 'Henry Borden'], 'id_nat': [116, 119, None], 'id_art': [None, None, 318]},
120: {'name': ['Jaguari'], 'id_nat': [120], 'id_art': [None]},
121: {'name': ['Paraibuna'], 'id_nat': [121], 'id_art': [None]},
122: {'name': ['Santa Branca'], 'id_nat': [122], 'id_art': [None]},
123: {'name': ['Funil'], 'id_nat': [123], 'id_art': [None]},
124: {'name': ['Lajes'], 'id_nat': [202], 'id_art': [132]},
#125: {'name': ['Santa Cecília', 'Santa Cecília Bombeamento'], 'id_nat': [125, None], 'id_art': [None, 298]},
125: {'name': ['Santa Cecília'], 'id_nat': [125], 'id_art': [None]},
126: {'name': ['Picada'], 'id_nat': [197], 'id_art': [None]},
127: {'name': ['Sobragi'], 'id_nat': [198], 'id_art': [None]},
129: {'name': ['Simplício', 'Anta'], 'id_nat': [None, 129], 'id_art': [126, 127]},
#130: {'name': ['Ilha dos Pombos'], 'id_nat': [130], 'id_art': [299]},
130: {'name': ['Ilha dos Pombos'], 'id_nat': [130], 'id_art': [None]},
131: {'name': ['Nilo Peçanha'], 'id_nat': [None], 'id_art': [131]},
132: {'name': ['Fontes'], 'id_nat': [202], 'id_art': [303]},
133: {'name': ['Pereira Passos'], 'id_nat': [202], 'id_art': [306]},
134: {'name': ['Salto Grande'], 'id_nat': [134], 'id_art': [None]},
135: {'name': ['Porto Estrela'], 'id_nat': [263], 'id_art': [None]},
139: {'name': ['Candonga'], 'id_nat': [149], 'id_art': [None]},
141: {'name': ['Baguari'], 'id_nat': [141], 'id_art': [None]},
143: {'name': ['Aimorés'], 'id_nat': [148], 'id_art': [None]},
144: {'name': ['Mascarenhas'], 'id_nat': [144], 'id_art': [None]},
148: {'name': ['Irapé'], 'id_nat': [255], 'id_art': [None]},
153: {'name': ['São Domingos'], 'id_nat': [154], 'id_art': [None]},
154: {'name': ['Itapebi'], 'id_nat': [188], 'id_art': [None]},
155: {'name': ['Retiro Baixo'], 'id_nat': [155], 'id_art': [None]},
156: {'name': ['Três Marias'], 'id_nat': [156], 'id_art': [None]},
162: {'name': ['Queimado'], 'id_nat': [158], 'id_art': [None]},
169: {'name': ['Sobradinho Incremental', 'Sobradinho'], 'id_nat': [168, 169], 'id_art': [None, None]},
172: {'name': ['Itaparica Incremental', 'Itaparica'], 'id_nat': [171, 172], 'id_art': [None, None]},
173: {'name': ['Moxotó'], 'id_nat': [173], 'id_art': [None]},
174: {'name': ['Paulo Afonso'], 'id_nat': [175], 'id_art': [None]},
176: {'name': ['Complexo Paulo Afonso-Moxotó'], 'id_nat': [176], 'id_art': [None]},
178: {'name': ['Xingó'], 'id_nat': [178], 'id_art': [None]},
180: {'name': ['Tocos', 'Tocos Vertimento'], 'id_nat': [201, None], 'id_art': [None, 317]},
181: {'name': ['Santana', 'Santana Vertimento'], 'id_nat': [203, None], 'id_art': [315, 304]},
182: {'name': ['Vigário'], 'id_nat': [None], 'id_art': [316]},
189: {'name': ['Pedra do Cavalo'], 'id_nat': [254], 'id_art': [None]},
190: {'name': ['Boa Esperança'], 'id_nat': [190], 'id_art': [None]},
192: {'name': ['Guilman-Amorin'], 'id_nat': [262], 'id_art': [None]},
193: {'name': ['Antônio Dias +Sá Carvalho'], 'id_nat': [183], 'id_art': [None]},
195: {'name': ['Jauru'], 'id_nat': [295], 'id_art': [None]},
196: {'name': ['Guaporé'], 'id_nat': [296], 'id_art': [None]},
203: {'name': ['Corumbá III'], 'id_nat': [23], 'id_art': [None]},
204: {'name': ['Cachoeira Caldeirão'], 'id_nat': [204], 'id_art': [None]},
215: {'name': ['Salto Pilão'], 'id_nat': [101], 'id_art': [None]},
217: {'name': ['Rosal'], 'id_nat': [196], 'id_art': [None]},
227: {'name': ['Sinop'], 'id_nat': [227], 'id_art': [None]},
228: {'name': ['Colider'], 'id_nat': [228], 'id_art': [None]},
229: {'name': ['Teles Pires'], 'id_nat': [229], 'id_art': [None]},
230: {'name': ['São Manoel'], 'id_nat': [230], 'id_art': [None]},
241: {'name': ['Salto do Rio Verdinho'], 'id_nat': [241], 'id_art': [None]},
249: {'name': ['Ourinhos'], 'id_nat': [249], 'id_art': [None]},
251: {'name': ['Serra da Mesa'], 'id_nat': [270], 'id_art': [None]},
252: {'name': ['Cana Brava'], 'id_nat': [191], 'id_art': [None]},
253: {'name': ['São Salvador'], 'id_nat': [253], 'id_art': [None]},
257: {'name': ['Peixe Angical'], 'id_nat': [257], 'id_art': [None]},
261: {'name': ['Lajeado'], 'id_nat': [273], 'id_art': [None]},
262: {'name': ['Salto'], 'id_nat': [294], 'id_art': [None]},
267: {'name': ['Estreito Tocantins'], 'id_nat': [271], 'id_art': [None]},
272: {'name': ['Curuá-Una'], 'id_nat': [277], 'id_art': [None]},
275: {'name': ['Tucuruí'], 'id_nat': [275], 'id_art': [None]},
276: {'name': ['Rondon 2'], 'id_nat': [145], 'id_art': [None]},
277: {'name': ['Balbina'], 'id_nat': [269], 'id_art': [None]},
278: {'name': ['Manso'], 'id_nat': [278], 'id_art': [None]},
279: {'name': ['Samuel'], 'id_nat': [279], 'id_art': [None]},
280: {'name': ['Coaracy Nunes'], 'id_nat': [280], 'id_art': [None]},
281: {'name': ['Ponte de Pedra'], 'id_nat': [281], 'id_art': [None]},
283: {'name': ['Santa Clara MG'], 'id_nat': [283], 'id_art': [None]},
284: {'name': ['Ferreira Gomes'], 'id_nat': [297], 'id_art': [None]},
285: {'name': ['Jirau'], 'id_nat': [285], 'id_art': [None]},
286: {'name': ['Santo Antônio do Jari'], 'id_nat': [290], 'id_art': [None]},
287: {'name': ['Santo Antônio'], 'id_nat': [287], 'id_art': [None]},
288: {'name': ['Posto', 'Belo Monte Artificial'], 'id_nat': [300, None], 'id_art': [None, 292]},
290: {'name': ['Espora'], 'id_nat': [99], 'id_art': [None]},
304: {'name': ['Itiquira I e II'], 'id_nat': [259], 'id_art': [None]},
305: {'name': ['Itiquira II'], 'id_nat': [252], 'id_art': [None]},
310: {'name': ['Dardanelos'], 'id_nat': [291], 'id_art': [None]},
311: {'name': ['Caçu'], 'id_nat': [247], 'id_art': [None]},
312: {'name': ['Barra dos Coqueiros'], 'id_nat': [248], 'id_art': [None]},
314: {'name': ['Pimental Artificial'], 'id_nat': [None], 'id_art': [302]},
315: {'name': ['Foz do Rio Claro'], 'id_nat': [261], 'id_art': [None]},
319: {'name': ['Mauá'], 'id_nat': [57], 'id_art': [None]},
921: {'name': ['Tocos_Lajes'], 'id_nat': [None], 'id_art': [921]},
}

incremental_stations = {
    34: {
        'name': 'Ilha Solteira',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2] - x[3] - x[4] - x[5],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2] + x[3] + x[4] + x[5],
        'dep_stations': [34, 33, 18, 99, 241, 261],
        'traveltime_natural': [0, 30, 18, 46, 28, 28],
        'traveltime_reserv': [0, 14, 6, 18, 9, 10],
        'type': 'Aggregate-Tiete',
    },
    238: {
        'name': 'Bariri',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [238, 237],
        'type': 'Dist. Incremental',
    },
    239: {
        'name': 'Ibitinga',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [239, 238],
        'traveltime_natural': [0, 24],
        'traveltime_reserv': [0, 18],
        'type': 'Aggregate-Tiete',
    },
    240: {
        'name': 'Promissão',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [240, 239],
        'type': 'Dist. Incremental',
    },
    242: {
        'name': 'Nova Avanhandava',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [242, 240],
        'traveltime_natural': [0, 42],
        'traveltime_reserv': [0, 12],
        'type': 'Aggregate-Tiete',
    },
    243: {
        'name': 'Três Irmãos',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [243, 242],
        'traveltime_natural': [0, 42],
        'traveltime_reserv': [0, 7],
        'type': 'Aggregate-Tiete',
    },
    245: {
        'name': 'Jupiá',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2],
        'dep_stations': [245, 34, 243],
        'traveltime_natural': [0, 5, 7],
        'traveltime_reserv': [0, 3, 5],
        'type': 'Aggregate-Tiete',
    },
    246: {
        'name': 'Porto Primavera',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2],
        'dep_stations': [246, 245, 154],
        'traveltime_natural': [0, 48, 32],
        'traveltime_reserv': [0, 24, 20],
        'type': 'Aggregate-Tiete',
    },
    266: {
        'name': 'Itaipu',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2],
        'dep_stations': [266, 63, 246],
        'traveltime_natural': [0, 48, 48],
        'traveltime_reserv': [0, 48, 48],
        'type': 'Aggregate-Tiete',
    },
    191: {
        'name': 'Cana Brava',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [191, 270],
        'type': 'Dist. Incremental',
    },
    253: {
        'name': 'São Salvador',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [253, 191],
        'type': 'Dist. Incremental',
    },
    257: {
        'name': 'Peixe Angical',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [257, 253],
        'type': 'Dist. Incremental',
    },
    273: {
        'name': 'Lajeado',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [273, 257],
        'type': 'Dist. Incremental',
    },
}

# Dictionary containing the formulae for the special stations
special_stations = {
    118: {
        'name': 'Billings',
        'type': 'Aggregate-Tiete',
        'formula': lambda x: 0.8 * x[0],
        'dep_stations': [119],
    },
    109: {
        'name': 'Pedreira',
        'type': 'Aggregate-Tiete',
        'formula': lambda x: x[0],
        'dep_stations': [118],
    },
    104: {
        'name': 'Traição',
        'type': 'Aggregate-Tiete',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [117, 118],
    },
    # A vazão incremental de Baixo Iguaçu (81) é obtida da vazão incremental de Salto Caxias (222)
    81: {
        'name': 'Baixo Iguaçu',
        'type': 'Baixo Iguaçu',
        'formula': lambda x: 0.8 * x[0],
        'dep_stations': [222],
    },
    # 116: {
    #     'name': 'Pedras',
    #     'type': 'Aggregate-Tiete',
    #     'formula': lambda x: x[0] - x[1],
    #     'dep_stations': [119, 118],
    # },
    # region Remover depois
    # 246: {
    #     'name': 'P. Primavera',
    #     'type': 'Aggregate-Tiete',
    #     'formula': lambda x: x[0] * 0.603,
    #     'dep_stations': [245],
    # },
    # endregion
    # 154: {
    #     'name': 'São Domingos',
    #     'type': 'Dist. Incremental',
    #     'formula': lambda x: x[0] * 0.179,
    #     'dep_stations': [246],
    # },
    238: {
        'name': 'Bariri Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.658,
        'dep_stations': [239],
    },
    240: {
        'name': 'Promissão Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.717,
        'dep_stations': [242],
    },
    191: {
        'name': 'Cana Brava Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.504,
        'dep_stations': [253],
    },
    257: {
        'name': 'Peixe Angical Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.488,
        'dep_stations': [273],
    },
    169: {
        'name': 'Sobradinho',
        'type': 'São Francisco',
        'formula': lambda x: x[0] + x[1] + x[2],
        'delay_time': [0, -2, -2],
        'dep_stations': [168, 156, 158],
    },
    172: {
        'name': 'Itaparica',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'dep_stations': [169],
    },
    173: {
        'name': 'Moxotó',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    175: {
        'name': 'P. Afonso 4',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    176: {
        'name': 'Comp. Moxotó',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    178: {
        'name': 'Comp. Moxotó',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    171: {
        'name': 'Itaparica Inc.',
        'type': 'Zeros',
    },
    921: {
        'name': 'Tocos_Lajes',
        'type': 'São Francisco',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [201, 202],
    },
}

calculated_stations_acomph = {
    2: {
        'name': 'Itutinga',
        'type': 'calculated',
        'formula': lambda x: x[0],
        'dep_stations': [1],
    },
    104: {
        'name': 'Traição',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [117, 118],
    },
    109: {
        'name': 'Pedreira',
        'type': 'calculated',
        'formula': lambda x: x[0],
        'dep_stations': [118],
    },
    119: {
        'name': 'Bill. + Pedras',
        'type': 'regressed_reverse',
        'formula': lambda x, a0, a1: a0 + a1*x[0],
        'dep_stations': [118],
    },
    116: {
        'name': 'Pedras',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [119, 118],
    },
    298: {
        'name': 'Santa Cecília Bombeamento',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: (((y * (119 / 190), 119)[190 < y <= 209], y - 90)[209 < y <= 250], 160)[y > 250]),
        'dep_stations': [125],
    },
    317: {
        'name': 'Tocos Vertimento',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: max(0, y - 25)),
        'dep_stations': [201],
    },
    203: {
        'name': 'Santana',
        'type': 'regressed',
        'formula': lambda x, a0, a1: a0 + a1*x[0],
        'dep_stations': [201],
    },
    315: {
        'name': 'Santana',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1] + x[2] + x[3],
        'dep_stations': [203, 201, 317, 298],
    },
    316: {
        'name': 'Vigário',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: min(y, 190)),
        'dep_stations': [315],
    },
    304: {
        'name': 'Santana Vertimento',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [315, 316],
    },
    127: {
        'name': 'Anta',
         'type': 'calculated',
         'formula': lambda x: x[0] - x[1] - x[2] + x[3],
         'dep_stations': [129, 298, 203, 304],
    },
    126: {
         'name': 'Simplício',
         'type': 'calculated',
         'formula': lambda x: x[0].apply(lambda y: (max(0, y - 90), 340)[y >= 430]),
         'dep_stations': [127],
    },
    131: {
        'name': 'Nilo Peçanha',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: min(y, 144)),
        'dep_stations': [316],
    },
    160: {
        'name': 'Ponte Nova',
        'type': 'calculated',
        'formula': lambda x: x[0]*(320/(4844-681-700)),
        'dep_stations': [161],
    },
    164: {
        'name': 'E. Souza',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1] - x[2],
        'dep_stations': [161, 117, 118],
    },
    # 168: {'name': 'Sobrad. Incr.',
    #     'formula': lambda x: x,
    #     'dep_stations': [ ],
    #},
    174: {
         'name': 'P.A.123',
         'type': 'calculated',
         'formula': lambda x: x[0],
         'dep_stations': [173],
    },
    175: {
          'name': 'P.A.4',
          'type': 'calculated',
          'formula': lambda x: x[0],
          'dep_stations': [173],
    },
    292: {
          'name': 'Belo Monte Principal',
          'type': 'belo_monte',
          'formula': lambda x, m: x[0].apply(lambda y: ((y - hydrogram_used[m], 13900)
                                                      [y > hydrogram_used[m] + 13900], 0)
                                                        [y < hydrogram_used[m]]),
          'dep_stations': [288],
    },
    132: {
        'name': 'Lajes',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1].apply(lambda y: min(y, 25)),
        'dep_stations': [202, 201],
    },
    303: {
        'name': 'Fontes',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: (17, y)[y < 17]) + (x[1] - x[2]).apply(lambda z: min(z, 34)),
        'dep_stations': [132, 316, 131],
    },
    306: {
        'name': 'Pereira Passos',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [303, 131],
    },
    318: {
        'name': 'Henry Borden',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1] + x[2] + 0.1 * (x[3] - x[1] - x[2]),
        'dep_stations': [116, 117, 118, 161],
    },
    921: {
        'name': 'Tocos_Lajes',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [201, 202],
    }
}
