#
# mlt_postos = { 1: {'name': ['Camargos'], 'id_nat': [1], 'id_art': [None], 'Bacia': ['Grande'], 'REE':['Parana'],
#                    'SUB':['SE'], 'Prod':[0,2076],'mlt':{'Jan':[242],'Fev':[220],'Mar':[196], 'Abr':[133], 'Mai':[100],'Jun':[85] }
#
# }
mlt_submarkets = {'Sudeste': [65805, 70900, 69326, 54954, 40060, 32662, 25728, 20616, 19716, 23606, 31431, 48039],
                  'Sul': [7474, 8215, 7010, 6483, 8494, 10387, 10887, 9929, 11549, 13135, 9270, 7390],
                  'Nordeste': [13512, 14256, 14160, 11574, 6988, 4611, 3799, 3314, 2959, 3224, 5303, 9837],
                  'Norte': [15597, 22630, 26690, 27001, 20391, 10664, 5246, 3189, 2274, 2390, 4029, 8271]
                  }
mlt_postos={
    1: {
        'name': ['Camargos'],
        'id_nat': [1],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['SE'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2076],
        'mlt': {
            'Jan': [242],
            'Fev': [220],
            'Mar': [196],
            'Abr': [133],
            'Mai': [100],
            'Jun': [85],
            'Jul': [71],
            'Ago': [61],
            'Set': [64],
            'Out': [76],
            'Nov': [108],
            'Dez': [176]
        }
    },
    2: {
        'name': ['Itutinga'],
        'id_nat': [2],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2437],
        'mlt': {
            'Jan': [242],
            'Fev': [220],
            'Mar': [196],
            'Abr': [133],
            'Mai': [100],
            'Jun': [85],
            'Jul': [71],
            'Ago': [61],
            'Set': [64],
            'Out': [76],
            'Nov': [108],
            'Dez': [176]
        }
    },
    6: {
        'name': ['Furnas'],
        'id_nat': [6],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.8130],
        'mlt': {
            'Jan': [1702],
            'Fev': [1588],
            'Mar': [1421],
            'Abr': [966],
            'Mai': [707],
            'Jun': [593],
            'Jul': [484],
            'Ago': [398],
            'Set': [413],
            'Out': [491],
            'Nov': [704],
            'Dez': [1204]
        }
    },
    7: {
        'name': ['M.Moraes'],
        'id_nat': [7],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.3471],
        'mlt': {
            'Jan': [1901],
            'Fev': [1788],
            'Mar': [1604],
            'Abr': [1093],
            'Mai': [797],
            'Jun': [664],
            'Jul': [541],
            'Ago': [445],
            'Set': [459],
            'Out': [545],
            'Nov': [777],
            'Dez': [1328]
        }
    },
    8: {
        'name': ['Estreito'],
        'id_nat': [8],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.5437],
        'mlt': {
            'Jan': [1943],
            'Fev': [1837],
            'Mar': [1649],
            'Abr': [1128],
            'Mai': [819],
            'Jun': [682],
            'Jul': [555],
            'Ago': [456],
            'Set': [468],
            'Out': [555],
            'Nov': [792],
            'Dez': [1328]
        }
    },
    9: {
        'name': ['Jaguara'],
        'id_nat': [9],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.3944],
        'mlt': {
            'Jan': [1959],
            'Fev': [1857],
            'Mar': [1668],
            'Abr': [1144],
            'Mai': [829],
            'Jun': [689],
            'Jul': [561],
            'Ago': [461],
            'Set': [472],
            'Out': [560],
            'Nov': [797],
            'Dez': [1357]
        }

    },
    10: {
        'name': ['Igarapava'],
        'id_nat': [10],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.1523],
        'mlt': {
            'Jan': [2008],
            'Fev': [1917],
            'Mar': [1723],
            'Abr': [1187],
            'Mai': [856],
            'Jun': [711],
            'Jul': [578],
            'Ago': [474],
            'Set': [483],
            'Out': [572],
            'Nov': [813],
            'Dez': [1381]
        }

    },
    11: {
        'name': ['Volta Grande'],
        'id_nat': [11],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2482],
        'mlt': {
            'Jan': [2120],
            'Fev': [2042],
            'Mar': [1838],
            'Abr': [1276],
            'Mai': [915],
            'Jun': [757],
            'Jul': [614],
            'Ago': [503],
            'Set': [509],
            'Out': [602],
            'Nov': [853],
            'Dez': [1445]
        }
    },
    12: {
        'name': ['PortoColombia'],
        'id_nat': [12],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2012],
        'mlt': {
            'Jan': [2393],
            'Fev': [2332],
            'Mar': [2108],
            'Abr': [1476],
            'Mai': [1053],
            'Jun': [865],
            'Jul': [699],
            'Ago': [571],
            'Set': [572],
            'Out': [678],
            'Nov': [957],
            'Dez': [1615]
        }

    },
    14: {
        'name': ['Caconde'],
        'id_nat': [14],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.8259],
        'mlt': {
            'Jan': [94],
            'Fev': [96],
            'Mar': [85],
            'Abr': [58],
            'Mai': [43],
            'Jun': [35],
            'Jul': [29],
            'Ago': [24],
            'Set': [25],
            'Out': [30],
            'Nov': [39],
            'Dez': [68]
        }

    },
    15: {
        'name': ['EuclidesdaCunha'],
        'id_nat': [15],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.7502],
        'mlt': {
            'Jan': [154],
            'Fev': [158],
            'Mar': [139],
            'Abr': [94],
            'Mai': [69],
            'Jun': [58],
            'Jul': [47],
            'Ago': [40],
            'Set': [41],
            'Out': [49],
            'Nov': [63],
            'Dez': [111]
        }
    },
    16: {
        'name': ['A.S.Oliveria'],
        'id_nat': [16],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2209],
        'mlt': {
            'Jan': [156],
            'Fev': [160],
            'Mar': [141],
            'Abr': [95],
            'Mai': [70],
            'Jun': [59],
            'Jul': [48],
            'Ago': [41],
            'Set': [42],
            'Out': [50],
            'Nov': [64],
            'Dez': [112]
        }
    },
    17: {
        'name': ['Maribondo'],
        'id_nat': [17],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.5183],
        'mlt': {
            'Jan': [3196],
            'Fev': [3262],
            'Mar': [2954],
            'Abr': [2117],
            'Mai': [1520],
            'Jun': [1277],
            'Jul': [1037],
            'Ago': [861],
            'Set': [848],
            'Out': [976],
            'Nov': [1324],
            'Dez': [2174]
        }
    },
    18: {
        'name': ['A.Vermelha'],
        'id_nat': [18],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.4625],
        'mlt': {
            'Jan': [3571],
            'Fev': [3698],
            'Mar': [3368],
            'Abr': [2433],
            'Mai': [1740],
            'Jun': [1467],
            'Jul': [1195],
            'Ago': [998],
            'Set': [976],
            'Out': [1124],
            'Nov': [1493],
            'Dez': [2410]
        }
    },
    20: {
        'name': ['BatalhaArtificial'],
        'id_nat': [22],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.3551],
        'mlt': {
            'Jan': [315],
            'Fev': [318],
            'Mar': [291],
            'Abr': [208],
            'Mai': [93],
            'Jun': [71],
            'Jul': [55],
            'Ago': [44],
            'Set': [37],
            'Out': [44],
            'Nov': [76],
            'Dez': [141]
        }
    },
    22: {
        'name': ['Batalha'],
        'id_nat': [22],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.3551],
        'mlt': {
            'Jan': [184],
            'Fev': [189],
            'Mar': [193],
            'Abr': [146],
            'Mai': [93],
            'Jun': [71],
            'Jul': [55],
            'Ago': [44],
            'Set': [37],
            'Out': [44],
            'Nov': [76],
            'Dez': [141]
        }
    },
    23: {
        'name': ['CorumbaIII'],
        'id_nat': [23],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.3471],
        'mlt': {
            'Jan': [260],
            'Fev': [288],
            'Mar': [291],
            'Abr': [230],
            'Mai': [144],
            'Jun': [105],
            'Jul': [82],
            'Ago': [65],
            'Set': [56],
            'Out': [73],
            'Nov': [121],
            'Dez': [195]
        }
    },
    24: {
        'name': ['Emborcacao'],
        'id_nat': [24],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [1.1582],
        'mlt': {
            'Jan': [860],
            'Fev': [863],
            'Mar': [833],
            'Abr': [604],
            'Mai': [385],
            'Jun': [295],
            'Jul': [235],
            'Ago': [189],
            'Set': [166],
            'Out': [197],
            'Nov': [344],
            'Dez': [639]
        }
    },
    25: {
        'name': ['NovaPonte'],
        'id_nat': [25],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.9669],
        'mlt': {
            'Jan': [508],
            'Fev': [514],
            'Mar': [486],
            'Abr': [362],
            'Mai': [249],
            'Jun': [195],
            'Jul': [160],
            'Ago': [130],
            'Set': [119],
            'Out': [146],
            'Nov': [220],
            'Dez': [366]
        }
    },
    28: {
        'name': ['C.Branco2'],
        'id_nat': [28],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.4169],
        'mlt': {
            'Jan': [614],
            'Fev': [625],
            'Mar': [593],
            'Abr': [449],
            'Mai': [308],
            'Jun': [242],
            'Jul': [200],
            'Ago': [166],
            'Set': [151],
            'Out': [182],
            'Nov': [270],
            'Dez': [442]
        }
    },
    31: {
        'name': ['Itumbiara'],
        'id_nat': [31],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.7027],
        'mlt': {
            'Jan': [2621],
            'Fev': [2725],
            'Mar': [2678],
            'Abr': [1999],
            'Mai': [1292],
            'Jun': [995],
            'Jul': [790],
            'Ago': [632],
            'Set': [559],
            'Out': [678],
            'Nov': [1113],
            'Dez': [1921]
        }
    },
    32: {
        'name': ['C.Dourada'],
        'id_nat': [32],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.2702],
        'mlt': {
            'Jan': [2743],
            'Fev': [2861],
            'Mar': [2812],
            'Abr': [2105],
            'Mai': [1363],
            'Jun': [1051],
            'Jul': [837],
            'Ago': [671],
            'Set': [594],
            'Out': [714],
            'Nov': [1167],
            'Dez': [2010]
        }
    },
    33: {
        'name': ['São Simão'],
        'id_nat': [33],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.6355],
        'mlt': {
            'Jan': [3951],
            'Fev': [4142],
            'Mar': [4144],
            'Abr': [3161],
            'Mai': [2068],
            'Jun': [1612],
            'Jul': [1295],
            'Ago': [1055],
            'Set': [948],
            'Out': [1121],
            'Nov': [1740],
            'Dez': [2921]
        }
    },
    34: {
        'name': ['Ilha Solteira'],
        'id_nat': [34],
        'id_art': [None],
        'Bacia': ['Alto Parana'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [5],
        'COD REF': [10],
        'Prod': [0.3869],
        'mlt': {
            'Jan': [8679],
            'Fev': [9116],
            'Mar': [8813],
            'Abr': [6618],
            'Mai': [4550],
            'Jun': [3720],
            'Jul': [3037],
            'Ago': [2545],
            'Set': [2412],
            'Out': [2783],
            'Nov': [3861],
            'Dez': [6173]
        }
    },
37: {
        'name': ['Barra Bonita Artficial'],
        'id_nat': [37],
        'id_art': [None],
        'Bacia': ['Tietê'],
        'REE': ['Sudeste'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [3],
        'COD REF': [1],
        'Prod': [0.1776],
        'mlt': {
            'Jan': [683],
            'Fev': [716],
            'Mar': [610],
            'Abr': [396],
            'Mai': [316],
            'Jun': [319],
            'Jul': [249],
            'Ago': [210],
            'Set': [225],
            'Out': [275],
            'Nov': [304],
            'Dez': [458]
        }
    },
    38: {
        'name': ['Bariri Artificial'],
        'id_nat': [38],
        'id_art': [None],
        'Bacia': ['Tietê'],
        'REE': ['Sudeste'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [3],
        'COD REF': [1],
        'Prod': [0.1848],
        'mlt': {
            'Jan': [765],
            'Fev': [805],
            'Mar': [689],
            'Abr': [452],
            'Mai': [361],
            'Jun': [364],
            'Jul': [284],
            'Ago': [241],
            'Set': [256],
            'Out': [309],
            'Nov': [343],
            'Dez': [512]
        }
    },
    39: {
        'name': ['Ibitinga Artificial'],
        'id_nat': [39],
        'id_art': [None],
        'Bacia': ['Tietê'],
        'REE': ['Sudeste'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [3],
        'COD REF': [1],
        'Prod': [0.1737],
        'mlt': {
            'Jan': [912],
            'Fev': [956],
            'Mar': [825],
            'Abr': [559],
            'Mai': [450],
            'Jun': [449],
            'Jul': [358],
            'Ago': [306],
            'Set': [322],
            'Out': [381],
            'Nov': [420],
            'Dez': [620]
        }
    },
    40: {
        'name': ['Promissão Artificial'],
        'id_nat': [40],
        'id_art': [None],
        'Bacia': ['Tietê'],
        'REE': ['Sudeste'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [3],
        'COD REF': [1],
        'Prod': [0.2130],
        'mlt': {
            'Jan': [1101],
            'Fev': [1155],
            'Mar': [1008],
            'Abr': [679],
            'Mai': [547],
            'Jun': [543],
            'Jul': [438],
            'Ago': [380],
            'Set': [398],
            'Out': [463],
            'Nov': [507],
            'Dez': [747]
        }
    },
    42: {
    'name': ['Nova Navanhadava Artificial'],
    'id_nat': [42],
    'id_art': [None],
    'Bacia': ['Tietê'],
    'REE': ['Sudeste'],
    'SUB': ['Sudeste'],
    'COD SUB': [1],
    'COD BACIA': [3],
    'COD REF': [1],
    'Prod': [0.2784],
    'mlt': {
        'Jan': [1184],
        'Fev': [1246],
        'Mar': [1083],
        'Abr': [728],
        'Mai': [583],
        'Jun': [580],
        'Jul': [466],
        'Ago': [403],
        'Set': [422],
        'Out': [493],
        'Nov': [541],
        'Dez': [799]
        }
    },
    43: {
    'name': ['Tres Irmaos Art'],
    'id_nat': [243],
    'id_art': [43],
    'Bacia': ['Tietê'],
    'REE': ['Sudeste'],
    'SUB': ['Sudeste'],
    'COD SUB': [1],
    'COD BACIA': [3],
    'COD REF': [1],
    'Prod': [0.4025],
    'mlt': {
        'Jan': [1240],
        'Fev': [1329],
        'Mar': [1169],
        'Abr': [797],
        'Mai': [625],
        'Jun': [624],
        'Jul': [503],
        'Ago': [436],
        'Set': [450],
        'Out': [524],
        'Nov': [572],
        'Dez': [836]
       }
    },
    47: {
        'name': ['Jurumirim'],
        'id_nat': [47],
        'id_art': [None],
        'Bacia': ['Paranapanema'],
        'REE': ['Paranapanema (SE)'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [0.2907],
        'mlt': {
            'Jan': [328],
            'Fev': [360],
            'Mar': [306],
            'Abr': [217],
            'Mai': [192],
            'Jun': [203],
            'Jul': [175],
            'Ago': [146],
            'Set': [158],
            'Out': [188],
            'Nov': [183],
            'Dez': [230]
        }
    },
    48: {
        'name': ['Piraju'],
        'id_nat': [48],
        'id_art': [None],
        'Bacia': ['Paranapanema'],
        'REE': ['Paranapanema (SE)'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [0.2306],
        'mlt': {
            'Jan': [335],
            'Fev': [368],
            'Mar': [314],
            'Abr': [222],
            'Mai': [196],
            'Jun': [209],
            'Jul': [180],
            'Ago': [150],
            'Set': [162],
            'Out': [193],
            'Nov': [187],
            'Dez': [235]
        }
    },
    49: {
        'name': ['Chavantes'],
        'id_nat': [49],
        'id_art': [None],
        'Bacia': ['Paranapanema'],
        'REE': ['Paranapanema (SE)'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [0.6177],
        'mlt': {
            'Jan': [510],
            'Fev': [535],
            'Mar': [446],
            'Abr': [321],
            'Mai': [300],
            'Jun': [319],
            'Jul': [276],
            'Ago': [228],
            'Set': [254],
            'Out': [303],
            'Nov': [286],
            'Dez': [349]
        }
    },
    50: {
        'name': ['L.N.Garcez'],
        'id_nat': [50],
        'id_art': [None],
        'Bacia': ['Paranapanema'],
        'REE': ['Paranapanema (SE)'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [0.1483],
        'mlt': {
            'Jan': [663],
            'Fev': [703],
            'Mar': [599],
            'Abr': [442],
            'Mai': [409],
            'Jun': [432],
            'Jul': [369],
            'Ago': [310],
            'Set': [338],
            'Out': [396],
            'Nov': [381],
            'Dez': [463]
        }
    },
    53: {
    'name': ['Canoas Ii'],
    'id_nat': [53],
    'id_art': [None],
    'Bacia': ['Paranapanema (SE)'],
    'REE': ['Paranapanema'],
    'SUB': ['Sudeste'],
    'COD SUB': [1],
    'COD BACIA': [4],
    'COD REF': [12],
    'Prod': [0.1288],
    'mlt': {
        'Jan': [673],
        'Fev': [716],
        'Mar': [611],
        'Abr': [452],
        'Mai': [417],
        'Jun': [441],
        'Jul': [376],
        'Ago': [316],
        'Set': [344],
        'Out': [403],
        'Nov': [388],
        'Dez': [472]
        }
    },
    54:  {
    'name': ['Canoas I'],
    'id_nat': [54],
    'id_art': [None],
    'Bacia': ['Paranapanema (SE)'],
    'REE': ['Paranapanema'],
    'SUB': ['Sudeste'],
    'COD SUB': [1],
    'COD BACIA': [4],
    'COD REF': [12],
    'Prod': [0.1489],
    'mlt': {
        'Jan': [697],
        'Fev': [743],
        'Mar': [636],
        'Abr': [471],
        'Mai': [434],
        'Jun': [459],
        'Jul': [392],
        'Ago': [330],
        'Set': [357],
        'Out': [418],
        'Nov': [404],
        'Dez': [490]
        }
    },
    55: {
        'name': ['Tibagi Mont'],
        'id_nat': [55],
        'id_art': [None],
        'Bacia': ['Paranapanema (SE)'],
        'REE': ['Paranapanema'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [None],
        'mlt': {
            'Jan': [188],
            'Fev': [188],
            'Mar': [159],
            'Abr': [118],
            'Mai': [145],
            'Jun': [184],
            'Jul': [186],
            'Ago': [150],
            'Set': [167],
            'Out': [218],
            'Nov': [178],
            'Dez': [160]
        }
    },
    57: {
    'name': ['Mauá'],
    'id_nat': [57],
    'id_art': [None],
    'Bacia': ['Paranapanema (S)'],
    'REE': ['Iguaçu'],
    'SUB': ['Sul'],
    'COD SUB': [2],
    'COD BACIA': [27],
    'COD REF': [11],
    'Prod': [1.0494],
    'mlt': {
        'Jan': [309],
        'Fev': [310],
        'Mar': [259],
        'Abr': [192],
        'Mai': [234],
        'Jun': [292],
        'Jul': [285],
        'Ago': [227],
        'Set': [256],
        'Out': [336],
        'Nov': [280],
        'Dez': [255]
        }
    },


}



